
class flight_consts():
    DEFAULT_TRIP_LENGTH = 5
    DEFAULT_ADULT_COUNT = 1
    DEFAULT_CHILDREN_COUNT = 0
    DEFAULT_INFANT_COUNT = 0
    DEFAULT_IS_ROUNDTRIP = True
    IATA_CODE_LENGTH = 3
    FLIGHT_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'